a = input("Enter your name :")
print("My name is ",a)
x = input("Enter first number:")
y = input("Enter second number:")
print(int(float(x))  + int(float(y)))
a = input("Enter your name :")
print("My name is ",a)
x = input("Enter first number:")
y = input("Enter second number:")
print(int(float(x))  - int(float(y)))
a = input("Enter your name :")
print("My name is ",a)
x = input("Enter first number:")
y = input("Enter second number:")
print(int(float(x))  * int(float(y)))
a = input("Enter your name :")
print("My name is ",a)
x = input("Enter first number:")
y = input("Enter second number:")
print(int(float(x))  / int(float(y)))
a = input("Enter your name :")
print("My name is ",a)
x = input("Enter first number:")
y = input("Enter second number:")
print(int(float(x))  ** int(float(y)))
a = input("Enter your name :")
print("My name is ",a)
x = input("Enter first number:")
y = input("Enter second number:")
print(int(float(x))  // int(float(y)))
a = input("Enter your name :")
print("My name is ",a)
x = input("Enter first number:")
y = input("Enter second number:")
print(int(float(x))  + int(float(y)))
a = input("Enter your name :")
print("My name is ",a)
x = input("Enter first number:")
y = input("Enter second number:")
print(int(float(x))  - int(float(y)))
a = input("Enter your name :")
print("My name is ",a)
x = input("Enter first number:")
y = input("Enter second number:")
print(int(float(x))  * int(float(y)))
a = input("Enter your name :")
print("My name is ",a)
x = input("Enter first number:")
y = input("Enter second number:")
print(int(float(x))  / int(float(y)))
a = input("Enter your name :")
print("My name is ",a)
x = input("Enter first number:")
y = input("Enter second number:")
print(int(float(x))  ** int(float(y)))
a = input("Enter your name :")
print("My name is ",a)
x = input("Enter first number:")
y = input("Enter second number:")
print(int(float(x))  // int(float(y)))
